### PR TITLE
Retrofit golang-1.9 from pyro to morty and upgrade to the latest

### PR DESCRIPTION
**Pull request by dtoubelis**
- This patch retrofits golang recipes from `pyro` branch to `morty`.
- This brings `golang-1.{6,7,8}` recipes to the same level as in `pyro` branch
- This also adds new `golang-1.9` recipe to `morty` upgraded to `1.9.7`, which is the latest maintenance release of `1.9` at present.

### CODE REVIEW

**Comment by dtoubelis** [comment]
As discussed in #28

**Comment by dtoubelis** [comment]
I should have squashed all commits though ;-)

**Comment by madisongh** [comment]
Overall the backport looks OK. Have you been able to run any test builds with these changes in place?

**Comment by dtoubelis** [comment]
Yup, run few builds with `1.9` in `morty`. Works as expected. I was little bit worried about patches when moving from `1.9.2` -> `1.9.7` but they caused no troubles. I haven't tried any of `1.8` or lower version but I would expect they would work the same as in Pyro.

**Comment by madisongh** [comment]
I have manually rebased the patches and included just the ones for go 1.9 and the bbclasses, excluding the rest of the pyro changes that got merged.

Thanks for your help with this!

**Comment by dtoubelis** [comment]
Awesome, thanks for your help.

**Pull request closed without merging**
